import '../../auth/domain/app_user.dart';
import 'resource_definition.dart';

const int _mb = 1024 * 1024;

const List<ResourceOption> organizationOptions = <ResourceOption>[
  ResourceOption('IPNU', 'IPNU'),
  ResourceOption('IPPNU', 'IPPNU'),
  ResourceOption('BERSAMA', 'Bersama'),
  ResourceOption('CBP_KPP', 'CBP KPP'),
];

const List<ResourceOption> spOrganizationOptions = <ResourceOption>[
  ResourceOption('IPNU', 'IPNU'),
  ResourceOption('IPPNU', 'IPPNU'),
];

const List<ResourceOption> spFilterOrganizationOptions = <ResourceOption>[
  ...spOrganizationOptions,
  ResourceOption('BERSAMA', 'Bersama'),
];

const List<ResourceOption> applicationStatusOptions = <ResourceOption>[
  ResourceOption('PENDING', 'Menunggu'),
  ResourceOption('DITERIMA', 'Diterima'),
  ResourceOption('DITOLAK', 'Ditolak'),
];

const List<ResourceOption> genderOptions = <ResourceOption>[
  ResourceOption('LAKI_LAKI', 'Laki-laki'),
  ResourceOption('PEREMPUAN', 'Perempuan'),
];

const Set<UserRole> _allRoles = <UserRole>{UserRole.pac, UserRole.cabang};
const Set<UserRole> _pacRole = <UserRole>{UserRole.pac};
const Set<UserRole> _cabangRole = <UserRole>{UserRole.cabang};

const ResourceDefinition wilayahResource = ResourceDefinition(
  key: 'wilayah',
  title: 'Wilayah',
  singular: 'Wilayah',
  primaryField: 'nama',
  accessRoles: _allRoles,
  createRoles: _pacRole,
  editRoles: _pacRole,
  deleteRoles: _pacRole,
  searchHint: 'Cari nama wilayah atau ketua...',
  emptyMessage: 'Belum ada ranting atau komisariat pada periode ini.',
  supportsCopyToActivePeriod: true,
  defaultSortKey: 'createdAt',
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'jenis',
      label: 'Jenis wilayah',
      kind: ResourceFieldKind.select,
      options: <ResourceOption>[
        ResourceOption('RANTING', 'Ranting'),
        ResourceOption('PK', 'Komisariat'),
      ],
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'nama',
      label: 'Nama wilayah',
      placeholder: 'Contoh: Ranting Desa X',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'ketua',
      label: 'Ketua / pimpinan',
      placeholder: 'Opsional',
      showInCard: true,
    ),
    FieldDefinition(
      key: 'kontak',
      label: 'Kontak',
      placeholder: 'Nomor HP (opsional)',
      showInCard: true,
    ),
    FieldDefinition(
      key: 'alamat',
      label: 'Alamat lengkap',
      kind: ResourceFieldKind.multiline,
      placeholder: 'Opsional',
      maxLines: 3,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'user',
      label: 'Pemilik data',
      showInForm: false,
      showInCard: true,
    ),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
      queryKey: 'jenis',
      label: 'Jenis wilayah',
      options: <ResourceOption>[
        ResourceOption('RANTING', 'Ranting'),
        ResourceOption('PK', 'Komisariat'),
      ],
    ),
    FilterDefinition(
      queryKey: 'userId',
      label: 'PAC',
      source: ResourceFilterSource.pacDirectory,
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('nama', 'Nama'),
    SortDefinition('jenis', 'Jenis'),
    SortDefinition('ketua', 'Ketua'),
    SortDefinition('kontak', 'Kontak'),
    SortDefinition('alamat', 'Alamat'),
    SortDefinition('createdAt', 'Terbaru'),
  ],
  stats: <StatDefinition>[StatDefinition('total', 'Total')],
);

const ResourceDefinition anggotaResource = ResourceDefinition(
  key: 'anggota',
  title: 'Anggota',
  singular: 'Anggota',
  primaryField: 'namaLengkap',
  accessRoles: _allRoles,
  searchHint: 'Cari nama, NIK, NIA, jabatan, atau nomor HP...',
  emptyMessage: 'Belum ada anggota pada periode yang dipilih.',
  supportsMemberVerification: true,
  supportsCopyPeriod: true,
  defaultSortKey: 'createdAt',
  defaultFilters: <String, String>{'status': 'PENDING'},
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'ANGGOTA',
    exportSheetName: 'Data Anggota',
    exportFilePrefix: 'Data_Anggota',
    qualifyWithPacFilter: true,
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(key: 'namaLengkap', header: 'Nama'),
      SpreadsheetColumnDefinition(key: 'nik', header: 'NIK'),
      SpreadsheetColumnDefinition(key: 'nia', header: 'NIA'),
      SpreadsheetColumnDefinition(
        key: 'jenisKelamin',
        header: 'Jenis Kelamin',
        kind: SpreadsheetValueKind.option,
      ),
      SpreadsheetColumnDefinition(key: 'tempatLahir', header: 'Tempat Lahir'),
      SpreadsheetColumnDefinition(
        key: 'tanggalLahir',
        header: 'Tanggal Lahir',
        kind: SpreadsheetValueKind.date,
      ),
      SpreadsheetColumnDefinition(key: 'alamatLengkap', header: 'Alamat'),
      SpreadsheetColumnDefinition(key: 'noHp', header: 'No HP'),
      SpreadsheetColumnDefinition(key: 'email', header: 'Email'),
      SpreadsheetColumnDefinition(key: 'jabatan', header: 'Jabatan'),
      SpreadsheetColumnDefinition(key: 'pekerjaan', header: 'Pekerjaan'),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'SD',
        kind: SpreadsheetValueKind.education,
        matchValue: 'SD',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'MI',
        kind: SpreadsheetValueKind.education,
        matchValue: 'MI',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'SMP',
        kind: SpreadsheetValueKind.education,
        matchValue: 'SMP',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'MTs',
        kind: SpreadsheetValueKind.education,
        matchValue: 'MTs',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'SMA',
        kind: SpreadsheetValueKind.education,
        matchValue: 'SMA',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'SMK',
        kind: SpreadsheetValueKind.education,
        matchValue: 'SMK',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'MAN',
        kind: SpreadsheetValueKind.education,
        matchValue: 'MAN',
      ),
      SpreadsheetColumnDefinition(
        key: 'pendidikans',
        header: 'KULIAH',
        kind: SpreadsheetValueKind.education,
        matchValue: 'KULIAH',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Makesta',
        kind: SpreadsheetValueKind.training,
        matchValue: 'MAKESTA',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Lakmud',
        kind: SpreadsheetValueKind.training,
        matchValue: 'LAKMUD',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Lakut',
        kind: SpreadsheetValueKind.training,
        matchValue: 'LAKUT',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Diklatama',
        kind: SpreadsheetValueKind.training,
        matchValue: 'DIKLATAMA',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Diklatmad',
        kind: SpreadsheetValueKind.training,
        matchValue: 'DIKLATMAD',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Latin',
        kind: SpreadsheetValueKind.training,
        matchValue: 'LATIN',
      ),
      SpreadsheetColumnDefinition(
        key: 'perkaderans',
        header: 'Latpel',
        kind: SpreadsheetValueKind.training,
        matchValue: 'LATPEL',
      ),
      SpreadsheetColumnDefinition(key: 'noRfid', header: 'No RFID'),
      SpreadsheetColumnDefinition(
        key: 'user',
        nestedKey: 'name',
        header: 'Dibuat Oleh',
        kind: SpreadsheetValueKind.nested,
      ),
      SpreadsheetColumnDefinition(
        key: 'periode',
        nestedKey: 'nama',
        header: 'Periode',
        kind: SpreadsheetValueKind.nested,
      ),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'namaLengkap',
      label: 'Nama lengkap',
      showInForm: false,
    ),
    FieldDefinition(key: 'nik', label: 'NIK', showInForm: false),
    FieldDefinition(key: 'nia', label: 'NIA', showInForm: false),
    FieldDefinition(key: 'email', label: 'Email', showInForm: false),
    FieldDefinition(key: 'foto', label: 'Foto', showInForm: false),
    FieldDefinition(key: 'noHp', label: 'Nomor HP', showInForm: false),
    FieldDefinition(
      key: 'jenisKelamin',
      label: 'Jenis kelamin',
      kind: ResourceFieldKind.select,
      options: genderOptions,
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tempatLahir',
      label: 'Tempat lahir',
      showInForm: false,
    ),
    FieldDefinition(
      key: 'tanggalLahir',
      label: 'Tanggal lahir',
      kind: ResourceFieldKind.date,
      showInForm: false,
    ),
    FieldDefinition(
      key: 'alamatLengkap',
      label: 'Alamat lengkap',
      kind: ResourceFieldKind.multiline,
      showInForm: false,
    ),
    FieldDefinition(
        key: 'jabatan', label: 'Jabatan', showInForm: false, showInCard: true),
    FieldDefinition(key: 'pekerjaan', label: 'Pekerjaan', showInForm: false),
    FieldDefinition(key: 'hobi', label: 'Hobi', showInForm: false),
    FieldDefinition(key: 'noRfid', label: 'Nomor RFID', showInForm: false),
    FieldDefinition(
      key: 'jenjangPendidikan',
      label: 'Jenjang pendidikan',
      showInForm: false,
    ),
    FieldDefinition(
      key: 'namaInstansiPendidikan',
      label: 'Instansi pendidikan',
      showInForm: false,
    ),
    FieldDefinition(
      key: 'status',
      label: 'Status verifikasi',
      kind: ResourceFieldKind.select,
      options: applicationStatusOptions,
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'alasanPenolakan',
      label: 'Alasan penolakan',
      kind: ResourceFieldKind.multiline,
      showInForm: false,
    ),
    FieldDefinition(
        key: 'wilayah', label: 'Wilayah', showInForm: false, showInCard: true),
    FieldDefinition(
        key: 'user', label: 'PAC', showInForm: false, showInCard: true),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
    FieldDefinition(
        key: 'pendidikans', label: 'Riwayat pendidikan', showInForm: false),
    FieldDefinition(
        key: 'perkaderans', label: 'Riwayat kaderisasi', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
      queryKey: 'status',
      label: 'Status',
      options: applicationStatusOptions,
    ),
    FilterDefinition(
      queryKey: 'userId',
      label: 'PAC',
      source: ResourceFilterSource.pacDirectory,
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('namaLengkap', 'Nama'),
    SortDefinition('status', 'Status'),
    SortDefinition('jenisKelamin', 'Jenis kelamin'),
    SortDefinition('noHp', 'Nomor HP'),
    SortDefinition('periode', 'Periode'),
    SortDefinition('user', 'Dibuat oleh'),
    SortDefinition('createdAt', 'Terbaru'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Diterima'),
    StatDefinition('lakiLaki', 'Laki-laki'),
    StatDefinition('perempuan', 'Perempuan'),
    StatDefinition('makesta', 'Makesta'),
    StatDefinition('lakmud', 'Lakmud'),
    StatDefinition('lakut', 'Lakut'),
    StatDefinition('latin', 'Latin'),
    StatDefinition('latpel', 'Latpel'),
    StatDefinition('diklatama', 'Diklatama'),
    StatDefinition('diklatmad', 'Diklatmad'),
  ],
);

const ResourceDefinition agendaResource = ResourceDefinition(
  key: 'agenda-kegiatan',
  title: 'Agenda kegiatan',
  singular: 'Kegiatan',
  primaryField: 'judul',
  accessRoles: _cabangRole,
  createRoles: _cabangRole,
  editRoles: _cabangRole,
  deleteRoles: _cabangRole,
  searchHint: 'Cari judul, deskripsi, atau lokasi...',
  emptyMessage: 'Belum ada agenda kegiatan pada periode ini.',
  defaultSortKey: 'tanggalMulai',
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'AGENDA_KEGIATAN',
    exportSheetName: 'Data Kegiatan',
    exportFilePrefix: 'Data_Kegiatan',
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(key: 'judul', header: 'Judul'),
      SpreadsheetColumnDefinition(
        key: 'tanggalMulai',
        header: 'Tanggal Mulai',
        kind: SpreadsheetValueKind.dateTime,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggalSelesai',
        header: 'Tanggal Selesai',
        kind: SpreadsheetValueKind.dateTime,
      ),
      SpreadsheetColumnDefinition(key: 'lokasi', header: 'Lokasi'),
      SpreadsheetColumnDefinition(
        key: 'status',
        header: 'Status',
        kind: SpreadsheetValueKind.option,
      ),
      SpreadsheetColumnDefinition(key: 'deskripsi', header: 'Deskripsi'),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'judul',
      label: 'Judul kegiatan',
      placeholder: 'Contoh: Rapat Pleno Gabungan',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(key: 'lokasi', label: 'Lokasi', showInCard: true),
    FieldDefinition(
      key: 'deskripsi',
      label: 'Deskripsi',
      kind: ResourceFieldKind.multiline,
      maxLines: 5,
    ),
    FieldDefinition(
      key: 'tanggalMulai',
      label: 'Mulai',
      kind: ResourceFieldKind.dateTime,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tanggalSelesai',
      label: 'Selesai',
      kind: ResourceFieldKind.dateTime,
      endAfterField: 'tanggalMulai',
      showInCard: true,
    ),
    FieldDefinition(
      key: 'warna',
      label: 'Warna agenda',
      kind: ResourceFieldKind.color,
      options: <ResourceOption>[
        ResourceOption('#ef4444', 'Merah'),
        ResourceOption('#f97316', 'Oranye'),
        ResourceOption('#eab308', 'Kuning'),
        ResourceOption('#16a34a', 'Hijau'),
        ResourceOption('#3b82f6', 'Biru'),
        ResourceOption('#a855f7', 'Ungu'),
        ResourceOption('#ec4899', 'Merah muda'),
        ResourceOption('#64748b', 'Abu-abu'),
      ],
      defaultValue: '#3b82f6',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'status',
      label: 'Status',
      kind: ResourceFieldKind.select,
      options: <ResourceOption>[
        ResourceOption('MENDATANG', 'Mendatang'),
        ResourceOption('BERLANGSUNG', 'Berlangsung'),
        ResourceOption('SELESAI', 'Selesai'),
      ],
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(key: 'user', label: 'Pemilik data', showInForm: false),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
      queryKey: 'status',
      label: 'Status waktu',
      options: <ResourceOption>[
        ResourceOption('MENDATANG', 'Mendatang'),
        ResourceOption('BERLANGSUNG', 'Berlangsung'),
        ResourceOption('SELESAI', 'Selesai'),
      ],
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('tanggalMulai', 'Tanggal'),
    SortDefinition('judul', 'Judul'),
    SortDefinition('lokasi', 'Lokasi'),
    SortDefinition('status', 'Status'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Total'),
    StatDefinition('mendatang', 'Mendatang'),
    StatDefinition('berlangsung', 'Berlangsung'),
    StatDefinition('selesai', 'Selesai'),
  ],
);

const ResourceDefinition arsipResource = ResourceDefinition(
  key: 'arsip',
  title: 'Arsip surat',
  singular: 'Arsip surat',
  primaryField: 'perihal',
  accessRoles: _allRoles,
  createRoles: _allRoles,
  editRoles: _allRoles,
  deleteRoles: _allRoles,
  searchHint: 'Cari nomor, perihal, pengirim, atau penerima...',
  emptyMessage: 'Belum ada arsip surat pada periode ini.',
  defaultSortKey: 'tanggal',
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'ARSIP_SURAT',
    templateFileName: 'Template_Import_Arsip_Surat.xlsx',
    exportSheetName: 'Arsip Surat',
    exportFilePrefix: 'Arsip_Surat_PAC',
    cabangExportFilePrefix: 'Arsip_Surat_Cabang',
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(
        key: 'noSurat',
        header: 'No. Surat',
        example: '001/A/IPNU/2025',
        width: 22,
      ),
      SpreadsheetColumnDefinition(
        key: 'jenisSurat',
        header: 'Jenis Surat',
        example: 'MASUK',
        kind: SpreadsheetValueKind.option,
        width: 14,
      ),
      SpreadsheetColumnDefinition(
        key: 'organisasi',
        header: 'Organisasi',
        example: 'IPNU',
        kind: SpreadsheetValueKind.option,
        optional: true,
        width: 12,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggal',
        header: 'Tanggal',
        example: '2025-01-15',
        kind: SpreadsheetValueKind.date,
        width: 14,
      ),
      SpreadsheetColumnDefinition(
        key: 'pengirimPenerima',
        header: 'Pengirim/Penerima',
        example: 'PC IPNU Magetan',
        width: 24,
      ),
      SpreadsheetColumnDefinition(
        key: 'perihal',
        header: 'Perihal',
        example: 'Contoh perihal surat',
        width: 30,
      ),
      SpreadsheetColumnDefinition(
        key: 'deskripsi',
        header: 'Deskripsi',
        example: '(opsional)',
        optional: true,
        width: 30,
      ),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'noSurat',
      label: 'Nomor surat',
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'organisasi',
      label: 'Organisasi',
      kind: ResourceFieldKind.select,
      options: organizationOptions,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'jenisSurat',
      label: 'Jenis surat',
      kind: ResourceFieldKind.select,
      options: <ResourceOption>[
        ResourceOption('MASUK', 'Surat masuk'),
        ResourceOption('KELUAR', 'Surat keluar'),
      ],
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'pengirimPenerima',
      label: 'Pengirim / penerima',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'tanggal',
      label: 'Tanggal surat',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'perihal',
      label: 'Perihal',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'deskripsi',
      label: 'Deskripsi',
      kind: ResourceFieldKind.multiline,
      maxLines: 4,
    ),
    FieldDefinition(
      key: 'file',
      label: 'Lampiran',
      kind: ResourceFieldKind.file,
      uploadPrefix: 'arsip',
      maxFileBytes: 2 * _mb,
      acceptedExtensions: <String>[
        'pdf',
        'doc',
        'docx',
        'ppt',
        'pptx',
        'jpg',
        'jpeg',
        'png',
        'webp',
      ],
    ),
    FieldDefinition(key: 'user', label: 'Pemilik data', showInForm: false),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
        queryKey: 'organisasi',
        label: 'Organisasi',
        options: organizationOptions),
    FilterDefinition(
      queryKey: 'jenisSurat',
      label: 'Jenis surat',
      options: <ResourceOption>[
        ResourceOption('MASUK', 'Surat masuk'),
        ResourceOption('KELUAR', 'Surat keluar'),
      ],
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('tanggal', 'Tanggal'),
    SortDefinition('noSurat', 'Nomor surat'),
    SortDefinition('perihal', 'Perihal'),
    SortDefinition('jenisSurat', 'Jenis'),
    SortDefinition('organisasi', 'Organisasi'),
    SortDefinition('pengirimPenerima', 'Pengirim / penerima'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Total'),
    StatDefinition('masuk', 'Masuk'),
    StatDefinition('keluar', 'Keluar'),
    StatDefinition('ipnu', 'IPNU'),
    StatDefinition('ippnu', 'IPPNU'),
    StatDefinition('bersama', 'Bersama'),
    StatDefinition('cbpkpp', 'CBP KPP'),
  ],
);

const ResourceDefinition berkasPimpinanResource = ResourceDefinition(
  key: 'berkas-pimpinan',
  title: 'Berkas pimpinan',
  singular: 'Berkas pimpinan',
  primaryField: 'nama',
  accessRoles: _allRoles,
  createRoles: _allRoles,
  editRoles: _allRoles,
  deleteRoles: _allRoles,
  searchHint: 'Cari nama atau catatan berkas...',
  emptyMessage: 'Belum ada berkas pimpinan pada periode ini.',
  defaultSortKey: 'tanggal',
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'BERKAS_PIMPINAN',
    templateFileName: 'Template_Import_Berkas.xlsx',
    exportSheetName: 'Berkas',
    exportFilePrefix: 'Berkas_PAC',
    cabangExportFilePrefix: 'Berkas_Cabang',
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(
        key: 'nama',
        header: 'Nama',
        example: 'Nama Berkas / Pimpinan',
        importAliases: <String>['Nama Pimpinan'],
        width: 25,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggal',
        header: 'Tanggal',
        example: '2025-01-01',
        kind: SpreadsheetValueKind.date,
        width: 15,
      ),
      SpreadsheetColumnDefinition(
        key: 'catatan',
        header: 'Catatan',
        example: '(opsional)',
        optional: true,
        width: 30,
      ),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'nama',
      label: 'Nama berkas',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'tanggal',
      label: 'Tanggal',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'catatan',
      label: 'Catatan',
      kind: ResourceFieldKind.multiline,
      maxLines: 4,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'file',
      label: 'File berkas',
      kind: ResourceFieldKind.file,
      uploadPrefix: 'berkas-pimpinan',
      maxFileBytes: 5 * _mb,
      requiredOnCreate: true,
      acceptedExtensions: <String>[
        'pdf',
        'doc',
        'docx',
        'ppt',
        'pptx',
        'jpg',
        'jpeg',
        'png',
        'webp',
      ],
    ),
    FieldDefinition(key: 'user', label: 'Pemilik data', showInForm: false),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
  ],
  sorts: <SortDefinition>[
    SortDefinition('tanggal', 'Tanggal'),
    SortDefinition('nama', 'Nama'),
    SortDefinition('createdAt', 'Terbaru'),
    SortDefinition('catatan', 'Catatan'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Total'),
    StatDefinition('bulanIni', 'Bulan ini'),
  ],
);

const ResourceDefinition berkasSpResource = ResourceDefinition(
  key: 'berkas-sp',
  title: 'Berkas SP',
  singular: 'Berkas SP',
  primaryField: 'nama',
  accessRoles: _cabangRole,
  createRoles: _cabangRole,
  editRoles: _cabangRole,
  deleteRoles: _cabangRole,
  searchHint: 'Cari nama atau catatan berkas SP...',
  emptyMessage: 'Belum ada berkas SP pada periode ini.',
  defaultSortKey: 'tanggalMulai',
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'BERKAS_SP',
    templateFileName: 'Template_Import_Berkas_SP.xlsx',
    exportSheetName: 'Berkas SP',
    exportFilePrefix: 'Berkas_SP',
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(
        key: 'nama',
        header: 'Nama Pimpinan',
        example: 'Nama Pengurus / Pimpinan',
        width: 25,
      ),
      SpreadsheetColumnDefinition(
        key: 'organisasi',
        header: 'Organisasi',
        example: 'IPNU',
        kind: SpreadsheetValueKind.option,
        width: 12,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggalMulai',
        header: 'Tanggal Mulai',
        example: '2025-01-01',
        kind: SpreadsheetValueKind.date,
        width: 15,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggalBerakhir',
        header: 'Tanggal Berakhir',
        example: '2027-01-01',
        kind: SpreadsheetValueKind.date,
        width: 15,
      ),
      SpreadsheetColumnDefinition(
        key: 'catatan',
        header: 'Catatan',
        example: '(opsional)',
        optional: true,
        width: 30,
      ),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'nama',
      label: 'Nama pimpinan',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'organisasi',
      label: 'Organisasi',
      kind: ResourceFieldKind.select,
      options: spOrganizationOptions,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tanggalMulai',
      label: 'Tanggal mulai',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tanggalBerakhir',
      label: 'Tanggal berakhir',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      endAfterField: 'tanggalMulai',
      showInCard: true,
    ),
    FieldDefinition(
      key: 'catatan',
      label: 'Catatan',
      kind: ResourceFieldKind.multiline,
      maxLines: 4,
    ),
    FieldDefinition(
      key: 'status',
      label: 'Status masa berlaku',
      kind: ResourceFieldKind.select,
      options: <ResourceOption>[
        ResourceOption('AKTIF', 'Aktif'),
        ResourceOption('HAMPIR_HABIS', 'Hampir habis'),
        ResourceOption('BERAKHIR_HARI_INI', 'Berakhir Hari Ini!'),
        ResourceOption('KEDALUWARSA', 'Kedaluwarsa'),
      ],
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'file',
      label: 'File SP',
      kind: ResourceFieldKind.file,
      uploadPrefix: 'berkas-sp',
      maxFileBytes: 2 * _mb,
      acceptedExtensions: <String>['pdf', 'doc', 'docx', 'ppt', 'pptx'],
    ),
    FieldDefinition(key: 'user', label: 'Pemilik data', showInForm: false),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
        queryKey: 'organisasi',
        label: 'Organisasi',
        options: spFilterOrganizationOptions),
  ],
  sorts: <SortDefinition>[
    SortDefinition('tanggalMulai', 'Tanggal mulai'),
    SortDefinition('tanggalBerakhir', 'Tanggal berakhir'),
    SortDefinition('nama', 'Nama'),
    SortDefinition('organisasi', 'Organisasi'),
    SortDefinition('status', 'Status'),
    SortDefinition('catatan', 'Catatan'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Total'),
    StatDefinition('ipnu', 'IPNU'),
    StatDefinition('ippnu', 'IPPNU'),
  ],
);

const ResourceDefinition pengajuanResource = ResourceDefinition(
  key: 'pengajuan-berkas',
  title: 'Pengajuan berkas',
  singular: 'Pengajuan',
  primaryField: 'keperluan',
  accessRoles: _allRoles,
  createRoles: _pacRole,
  editRoles: _pacRole,
  deleteRoles: _allRoles,
  searchHint: 'Cari nomor surat, keperluan, atau pengaju...',
  emptyMessage: 'Belum ada pengajuan pada periode ini.',
  defaultSortKey: 'createdAt',
  pendingOnlyEdit: true,
  supportsStatusReview: true,
  spreadsheet: ResourceSpreadsheetDefinition(
    module: 'PENGAJUAN_BERKAS',
    exportSheetName: 'Pengajuan PAC',
    exportFilePrefix: 'Pengajuan_PAC',
    qualifyWithPacFilter: true,
    columns: <SpreadsheetColumnDefinition>[
      SpreadsheetColumnDefinition(key: 'noSurat', header: 'No Surat'),
      SpreadsheetColumnDefinition(
        key: 'penerima',
        header: 'Penerima',
        kind: SpreadsheetValueKind.option,
      ),
      SpreadsheetColumnDefinition(
        key: 'tanggal',
        header: 'Tanggal',
        kind: SpreadsheetValueKind.date,
      ),
      SpreadsheetColumnDefinition(key: 'keperluan', header: 'Keperluan'),
      SpreadsheetColumnDefinition(key: 'deskripsi', header: 'Deskripsi'),
      SpreadsheetColumnDefinition(
        key: 'status',
        header: 'Status',
        kind: SpreadsheetValueKind.option,
      ),
      SpreadsheetColumnDefinition(
        key: 'user',
        nestedKey: 'name',
        header: 'Pengaju',
        kind: SpreadsheetValueKind.nested,
        cabangOnly: true,
      ),
      SpreadsheetColumnDefinition(
        key: 'alasanPenolakan',
        header: 'Alasan Penolakan',
        omitWhenAllEmpty: true,
      ),
    ],
  ),
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'noSurat',
      label: 'Nomor surat',
      placeholder: 'Contoh: 001/PAC/I/2026',
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'penerima',
      label: 'Penerima',
      kind: ResourceFieldKind.select,
      options: organizationOptions,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tanggal',
      label: 'Tanggal',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'keperluan',
      label: 'Keperluan',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'deskripsi',
      label: 'Deskripsi',
      kind: ResourceFieldKind.multiline,
      maxLines: 4,
    ),
    FieldDefinition(
      key: 'file',
      label: 'File lampiran',
      kind: ResourceFieldKind.file,
      uploadPrefix: 'pengajuan-berkas',
      maxFileBytes: 2 * _mb,
      acceptedExtensions: <String>[
        'pdf',
        'doc',
        'docx',
        'ppt',
        'pptx',
        'jpg',
        'jpeg',
        'png',
        'webp',
      ],
      requiredOnCreate: true,
    ),
    FieldDefinition(
      key: 'status',
      label: 'Status',
      kind: ResourceFieldKind.select,
      options: applicationStatusOptions,
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'alasanPenolakan',
      label: 'Alasan penolakan',
      kind: ResourceFieldKind.multiline,
      showInForm: false,
    ),
    FieldDefinition(
        key: 'user', label: 'Pengaju', showInForm: false, showInCard: true),
    FieldDefinition(key: 'periodePac', label: 'Periode PAC', showInForm: false),
    FieldDefinition(
        key: 'periodeCabang', label: 'Periode Cabang', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
        queryKey: 'status', label: 'Status', options: applicationStatusOptions),
    FilterDefinition(
        queryKey: 'penerima', label: 'Penerima', options: organizationOptions),
    FilterDefinition(
      queryKey: 'userId',
      label: 'PAC',
      source: ResourceFilterSource.pacDirectory,
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('createdAt', 'Terbaru'),
    SortDefinition('tanggal', 'Tanggal surat'),
    SortDefinition('noSurat', 'Nomor surat'),
    SortDefinition('keperluan', 'Keperluan'),
    SortDefinition('penerima', 'Penerima'),
    SortDefinition('status', 'Status'),
    SortDefinition('pengaju', 'Pengaju'),
  ],
  stats: <StatDefinition>[
    StatDefinition('total', 'Total'),
    StatDefinition('pending', 'Menunggu'),
    StatDefinition('diterima', 'Diterima'),
    StatDefinition('ditolak', 'Ditolak'),
    StatDefinition('ipnu', 'IPNU'),
    StatDefinition('ippnu', 'IPPNU'),
    StatDefinition('bersama', 'Bersama'),
    StatDefinition('cbpKpp', 'CBP KPP'),
  ],
);

const ResourceDefinition presensiResource = ResourceDefinition(
  key: 'presensi',
  title: 'Presensi',
  singular: 'Presensi',
  primaryField: 'namaKegiatan',
  accessRoles: _allRoles,
  createRoles: _allRoles,
  editRoles: _allRoles,
  deleteRoles: _allRoles,
  searchHint: 'Cari kegiatan, tempat, atau penyelenggara...',
  emptyMessage: 'Belum ada sesi presensi pada periode ini.',
  defaultSortKey: 'tanggal',
  supportsParticipants: true,
  fields: <FieldDefinition>[
    FieldDefinition(
      key: 'namaKegiatan',
      label: 'Nama kegiatan',
      requiredOnCreate: true,
      requiredOnEdit: true,
    ),
    FieldDefinition(
      key: 'penyelenggara',
      label: 'Penyelenggara',
      defaultValue: 'PC IPNU IPPNU Magetan',
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tempat',
      label: 'Lokasi / tempat',
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'tanggal',
      label: 'Tanggal kegiatan',
      kind: ResourceFieldKind.date,
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'jamMulai',
      label: 'Jam mulai',
      kind: ResourceFieldKind.time,
      defaultValue: '08:00',
      requiredOnCreate: true,
      requiredOnEdit: true,
      showInCard: true,
    ),
    FieldDefinition(
      key: 'jamSelesai',
      label: 'Jam selesai',
      kind: ResourceFieldKind.time,
      defaultValue: '12:00',
      requiredOnCreate: true,
      requiredOnEdit: true,
      endAfterField: 'jamMulai',
      showInCard: true,
    ),
    FieldDefinition(
      key: 'isActive',
      label: 'Sesi diaktifkan',
      kind: ResourceFieldKind.toggle,
      defaultValue: true,
      showInForm: false,
    ),
    FieldDefinition(
      key: 'status',
      label: 'Status saat ini',
      kind: ResourceFieldKind.select,
      options: <ResourceOption>[
        ResourceOption('OPEN', 'Terbuka'),
        ResourceOption('CLOSED', 'Tertutup'),
      ],
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(
      key: '_count',
      label: 'Jumlah peserta',
      showInForm: false,
      showInCard: true,
    ),
    FieldDefinition(key: 'user', label: 'Pemilik data', showInForm: false),
    FieldDefinition(key: 'periode', label: 'Periode', showInForm: false),
  ],
  filters: <FilterDefinition>[
    FilterDefinition(
      queryKey: 'status',
      label: 'Status sesi',
      options: <ResourceOption>[
        ResourceOption('OPEN', 'Terbuka'),
        ResourceOption('CLOSED', 'Ditutup'),
      ],
    ),
  ],
  sorts: <SortDefinition>[
    SortDefinition('tanggal', 'Tanggal'),
    SortDefinition('namaKegiatan', 'Nama kegiatan'),
    SortDefinition('tempat', 'Tempat'),
    SortDefinition('isActive', 'Status'),
    SortDefinition('jamMulai', 'Jam mulai'),
  ],
  stats: <StatDefinition>[StatDefinition('total', 'Total')],
);

const List<ResourceDefinition> resourceDefinitions = <ResourceDefinition>[
  wilayahResource,
  anggotaResource,
  agendaResource,
  arsipResource,
  berkasPimpinanResource,
  berkasSpResource,
  pengajuanResource,
  presensiResource,
];

ResourceDefinition resourceDefinitionFor(String key) {
  for (final ResourceDefinition definition in resourceDefinitions) {
    if (definition.key == key) return definition;
  }
  throw ArgumentError.value(key, 'key', 'Resource tidak terdaftar');
}
